### ISSUE TITLE
Broken URL.

### ISSUE THREAD

**Issue by harisaamin** [codeforpakistan/Open-Data-API#14]
28: ## Example Request
29: ~~~~
30: curl http://104.131.115.46:555/api/v1/open_data/education/all?limit=2

In the README file, the argument for this curl command is a broken link.

**Comment by harisaamin** [comment]
This issue was moved to harisaamin/Open-Data-API#19

**Comment by yousharizvi** [comment]
This issue was moved to yousharizvi1/Open-Data-API#15
