### ISSUE TITLE
Broken URL for downloading data sets.

### ISSUE THREAD

**Issue by harisaamin** [codeforpakistan/Open-Data-API#15]
19: ## To Download Data Sets
20: ~~~~
21: curl http://104.131.115.46:555/api/v1/open_data/downloads/<filename>

The argument for this curl command to download data sets, is a broken link.

**Comment by harisaamin** [comment]
This issue was moved to harisaamin/Open-Data-API#20

**Comment by yousharizvi** [comment]
This issue was moved to yousharizvi1/Open-Data-API#16
