### ISSUE TITLE
Variable sequencing. 

### ISSUE THREAD

**Issue by harisaamin** [codeforpakistan/Open-Data-API#2]
17: open_data_df = pd.read_excel(ATTENDANCE_DATA_FILE, 0, index_col=None, na_values=['NA'])
18: cplc_data_df = pd.read_excel(CPLC_DATA, 'Combined 2013', index_col=None, na_values=['NA'])
19: **cplc_idx_size = len(cplc_data_df.index._data)** 
20: **idx_size = len(open_data_df.index._data)**

The sequence of the len functions in line 19 and 20 needs to follow the sequence given for the **open_data_df** and **cplc_data_df** variables in line 17 and 18.

**Comment by harisaamin** [comment]
This issue was moved to harisaamin/Open-Data-API#7

**Comment by yousharizvi** [comment]
This issue was moved to yousharizvi1/Open-Data-API#3

**Comment by QuinnWilton** [comment]
❤️ 💚 💙 💛 💜
