### ISSUE TITLE
Replacing iterator variable.

### ISSUE THREAD

**Issue by harisaamin** [codeforpakistan/Open-Data-API#3]
for **i** in range(idx_size): #remove i wiht proper name
        clean = {}
        row_dict = cplc_data_df.iloc[**i**].to_dict()
        for key in row_dict:
            if type(row_dict[key]) is numpy.float64 and not math.isnan(row_dict[key]):
                clean[key] = int(row_dict[key])
            elif type(row_dict[key]) is numpy.float64 and math.isnan(row_dict[key]):
                clean[key] = None
            else:
                clean[key] = row_dict[key]
        to_return['data'].append(clean)
    to_return['data'] = to_return['data'][start_idx:end]
    to_return['end_idx'] = end
    to_return['limit'] = limit

The **i** variable needs to be changed to the actual thing which is being referenced in the data, i.e. the field.

**Comment by harisaamin** [comment]
This issue was moved to harisaamin/Open-Data-API#9

**Comment by QuinnWilton** [comment]
❤️ 💚 💙 💛 💜

**Comment by yousharizvi** [comment]
This issue was moved to yousharizvi1/Open-Data-API#4
