### ISSUE TITLE
Shortening inline if/else statements to code blocks.

### ISSUE THREAD

**Issue by harisaamin** [codeforpakistan/Open-Data-API#4]
77: start_idx = int(request.args.get('start_idx') if request.args.get('start_idx') else 0)
78: limit = int(request.args.get('limit') if request.args.get('limit') else 30)

The two inline statements above could be changed to code blocks for better readability. This change would be trading off Python's syntactical edge which enables one to read code like an algorithm, but would help shorten the line length and help with better readability.

**Comment by harisaamin** [comment]
This issue was moved to harisaamin/Open-Data-API#8

**Comment by QuinnWilton** [comment]
❤️ 💚 💙 💛 💜

**Comment by yousharizvi** [comment]
This issue was moved to yousharizvi1/Open-Data-API#5
