### ISSUE TITLE
Single assignment statement - block to inline.

### ISSUE THREAD

**Issue by harisaamin** [codeforpakistan/Open-Data-API#5]
**98:   to_return = {
 99:     "columns": []
 100:   }**

This could be turned from block to inline for better readability, as it is just an assignment.

**Comment by harisaamin** [comment]
This issue was moved to harisaamin/Open-Data-API#10

**Comment by yousharizvi** [comment]
This issue was moved to yousharizvi1/Open-Data-API#6
